<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Produk yang baru terjual oleh reseller__54e8cb</name>
   <tag></tag>
   <elementGuidId>1383dc7f-28c8-46cc-8b7f-552a120f33c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='splide08-slide01']/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#splide08-slide01 > div > div.productCard > div.productCard__head > div.productCard__imageHolder > a > img.productCard__image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://evermos-production.s3.ap-southeast-1.amazonaws.com/brand/gorilla-instan/product/image/5f9674117ab8a.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productCard__image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://evermos-production.s3.ap-southeast-1.amazonaws.com/brand/gorilla-instan/product/image/5f9674117ab8a.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lazy</name>
      <type>Main</type>
      <value>loaded</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide08-slide01&quot;)/div[1]/div[@class=&quot;productCard&quot;]/div[@class=&quot;productCard__head&quot;]/div[@class=&quot;productCard__imageHolder&quot;]/a[1]/img[@class=&quot;productCard__image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='splide08-slide01']/div/div/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://evermos-production.s3.ap-southeast-1.amazonaws.com/brand/gorilla-instan/product/image/5f9674117ab8a.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div[2]/ul/li/div/div/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
